# Generated by Django 5.1.6 on 2025-03-07 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0004_alter_department_deptname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('aadharno', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('dob', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('licenseno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('regno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=20)),
                ('driver', models.ManyToManyField(to='dbapp.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
                ('aadhar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dbapp.aadhar')),
            ],
        ),
    ]
