# Generated by Django 5.1.6 on 2025-03-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0006_table1_table2_employeedup'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
